### ISSUE TITLE
just a discussion

### ISSUE THREAD

**Issue by justin2004** [cmungall/semantic-sql#1]
> important: Lack of composability. No equivalent of SQL VIEWs

I think your https://github.com/cmungall/sparqlprog is an interesting take on adding composability right above SPARQL.

But another way to add composability is to just run SPARQL `insert where` queries and insert into named graphs as triples get added or modified. So it would be like materializing a SQL view, right? Then the inserted triples would be available for select queries, of course, thus basically giving the result of the `insert where` queries first class status (and composability).

**Comment by cmungall** [comment]
Thanks, and I'm glad you saw the connection to sparqlprog! Indeed, yes you can get composition akin to materialized views with inserts.  Afaik there is no "virtual construct" through this would be useful.  I haven't looked too much into SPIN or SHACL for this kind of thing. So I may be overstating my case... but the broader point may be that this is so much easier with a sql stack. Thanks for your comments and apologies I'm having problems putting a github handle to a name, have we met?

**Comment by justin2004** [comment]
On Tue, May 04, 2021 at 10:07:52PM -0700, Chris Mungall wrote:
> Thanks, and I'm glad you saw the connection to sparqlprog! Indeed, yes you can get composition akin to materialized views with inserts.
> Afaik there is no "virtual construct" through this would be useful. 
the closest thing i know is Stardog's stored queries.
"Many queries tend to be executed often and it’s handy to call them by
name rather than compose the query string each time."
https://www.stardog.com/labs/blog/stored-query-service/

> I haven't looked too much into SPIN or SHACL for this kind of
> thing. So I may be overstating my case... 
when it comes to inference i think SHACL is mostly used for forward
chaining with materialization.
the inference part is rather new too. i wrapped that new functionality for
quick starts here:
https://github.com/justin2004/shacl_box

> but the broader point may be that this is so much easier with a sql stack. 
after all i think AWS Neptune is a RDBMS under the hood, right? :)
but you have to bring your own reasoning.

> Thanks for your
> comments and apologies I'm having problems putting a github handle to a name, have we met?
we have not. i just came across your work when i was looking for a
way to convert from prolog/datalog to SPARQL.

**Comment by cmungall** [comment]
Thanks @justin2004 !

**Comment by cmungall** [comment]
closing for now, feel free to continue here: https://github.com/cmungall/semantic-sql/discussions
